# Generated by Django 2.2 on 2019-05-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='analysisterm0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term0', to='models.Term', verbose_name='分析項目0'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term1', to='models.Term', verbose_name='分析項目1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term2', to='models.Term', verbose_name='分析項目2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term3', to='models.Term', verbose_name='分析項目3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term4', to='models.Term', verbose_name='分析項目4'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term5', to='models.Term', verbose_name='分析項目5'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term6', to='models.Term', verbose_name='分析項目6'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term7', to='models.Term', verbose_name='分析項目7'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term8', to='models.Term', verbose_name='分析項目8'),
        ),
        migrations.AddField(
            model_name='customer',
            name='analysisterm9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term9', to='models.Term', verbose_name='分析項目9'),
        ),
    ]
