# Generated by Django 2.2 on 2019-05-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190513_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm0',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm5',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm6',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm7',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm8',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='analysisterm9',
        ),
        migrations.CreateModel(
            name='SamplingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='採水サイト名称')),
                ('analysisterm0', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term0', to='models.Term', verbose_name='分析項目0')),
                ('analysisterm1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term1', to='models.Term', verbose_name='分析項目1')),
                ('analysisterm10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term10', to='models.Term', verbose_name='分析項目10')),
                ('analysisterm11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term11', to='models.Term', verbose_name='分析項目11')),
                ('analysisterm12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term12', to='models.Term', verbose_name='分析項目12')),
                ('analysisterm13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term13', to='models.Term', verbose_name='分析項目13')),
                ('analysisterm14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term14', to='models.Term', verbose_name='分析項目14')),
                ('analysisterm2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term2', to='models.Term', verbose_name='分析項目2')),
                ('analysisterm3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term3', to='models.Term', verbose_name='分析項目3')),
                ('analysisterm4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term4', to='models.Term', verbose_name='分析項目4')),
                ('analysisterm5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term5', to='models.Term', verbose_name='分析項目5')),
                ('analysisterm6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term6', to='models.Term', verbose_name='分析項目6')),
                ('analysisterm7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term7', to='models.Term', verbose_name='分析項目7')),
                ('analysisterm8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term8', to='models.Term', verbose_name='分析項目8')),
                ('analysisterm9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term9', to='models.Term', verbose_name='分析項目9')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='models.Customer')),
            ],
            options={
                'verbose_name_plural': '採水サイト',
                'unique_together': {('analysisterm0', 'analysisterm1', 'analysisterm2', 'analysisterm3', 'analysisterm4', 'analysisterm5', 'analysisterm6', 'analysisterm7', 'analysisterm8', 'analysisterm9', 'analysisterm10', 'analysisterm11', 'analysisterm12', 'analysisterm13', 'analysisterm14')},
            },
        ),
    ]
