# Generated by Django 2.2 on 2019-05-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190513_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term0', to='models.Term', verbose_name='分析項目0'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term1', to='models.Term', verbose_name='分析項目1'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term10', to='models.Term', verbose_name='分析項目10'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term11', to='models.Term', verbose_name='分析項目11'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term12', to='models.Term', verbose_name='分析項目12'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term13', to='models.Term', verbose_name='分析項目13'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term14', to='models.Term', verbose_name='分析項目14'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term2', to='models.Term', verbose_name='分析項目2'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term3', to='models.Term', verbose_name='分析項目3'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term4', to='models.Term', verbose_name='分析項目4'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term5', to='models.Term', verbose_name='分析項目5'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term6', to='models.Term', verbose_name='分析項目6'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term7', to='models.Term', verbose_name='分析項目7'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term8', to='models.Term', verbose_name='分析項目8'),
        ),
        migrations.AlterField(
            model_name='samplingsite',
            name='analysisterm9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term9', to='models.Term', verbose_name='分析項目9'),
        ),
    ]
